sudo: required
services:
  - docker

before_install:
  - docker build -t dotadro/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dotadro/react-test npm test

after_success:
  - docker build -t dotadro/multi-client ./client
  - docker build -t dotadro/multi-nginx ./nginx
  - docker build -t dotadro/multi-server ./server
  - docker build -t dotadro/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images to push to docker hub
  - docker push dotadro/multi-client
  - docker push dotadro/multi-nginx
  - docker push dotadro/multi-server
  - docker push dotadro/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-184426512248
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
